# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SyslogScan-Daemon
version:      0.41
version_from: lib/SyslogScan/Daemon.pm
installdirs:  site
requires:
    Daemon::Generic:               0
    Mail::SendVarious:             0
    Plugins:                       0
    Sys::Hostname:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
